aws_region       = "eu-north-1"
vpc_cidr         = "10.0.0.0/16"
cluster_name     = "commitlab-cluster"
app_name         = "commitlab-app"
hosted_zone_name = "commit.local"
environment_tag  = "dimatest"